export const user=[
    {
        name:'A',
        age:'23',
        email:'A@gmail.com',
        id:'101'
    },
    {
        name:'B',
        age:'22',
        email:'B@gmail.com',
        id:'102'
    },
    {
        name:'C',
        age:'21',
        email:'C@gmail.com',
        id:'103'
    },
    {
        name:'D',
        age:'19',
        email:'D@gmail.com',
        id:'104'
    }
]